#!/usr/bin/env bash
# Generate docker/otel/snmp-collector.yaml from default.exporters.
# Community is NOT written here; it is resolved at runtime via ${env:SNMP_COMMUNITY}.
set -euo pipefail

CH_CONTAINER="${CH_CONTAINER:-akvorado-clickhouse-1}"
EXTRA_FILE="${EXTRA_FILE:-$(dirname "$0")/snmp-extra-targets.txt}"
OUT="$(dirname "$0")/snmp-collector.yaml"

# Source 1: exporters discovered from the flow database.
mapfile -t ADDRS < <(docker exec -i "$CH_CONTAINER" clickhouse-client -q \
  "SELECT DISTINCT replaceRegexpOne(toString(ExporterAddress),'^::ffff:','') FROM default.exporters ORDER BY 1" 2>/dev/null || true)

# Source 2: optional manually-maintained targets (gitignored), one IP per line, '#' comments allowed.
if [ -f "$EXTRA_FILE" ]; then
  while IFS= read -r line; do
    line="${line%%#*}"; line="$(echo "$line" | tr -d '[:space:]')"
    [ -n "$line" ] && ADDRS+=("$line")
  done < "$EXTRA_FILE"
fi

# Union: dedup, stable sorted order.
mapfile -t ADDRS < <(printf '%s\n' "${ADDRS[@]}" | sed '/^$/d' | sort -u)

if [ "${#ADDRS[@]}" -eq 0 ]; then
  echo "No SNMP targets: default.exporters is empty and no $EXTRA_FILE provided." >&2
  exit 1
fi

{
  echo "# GENERATED by gen-snmp-targets.sh — do not edit; do not commit."
  echo "receivers:"
  for ip in "${ADDRS[@]}"; do
    key="${ip//./_}"
    cat <<YAML
  snmp/${key}:
    collection_interval: 60s
    endpoint: udp://${ip}:161
    version: v2c
    community: \${env:SNMP_COMMUNITY}
    resource_attributes:
      snmp.interface.index:
        oid: "1.3.6.1.2.1.2.2.1.1"
    metrics:
      snmp.interface.in.octets:
        unit: By
        sum: {aggregation: cumulative, monotonic: true, value_type: int}
        column_oids:
          - oid: "1.3.6.1.2.1.31.1.1.1.6"
            resource_attributes: [snmp.interface.index]
      snmp.interface.out.octets:
        unit: By
        sum: {aggregation: cumulative, monotonic: true, value_type: int}
        column_oids:
          - oid: "1.3.6.1.2.1.31.1.1.1.10"
            resource_attributes: [snmp.interface.index]
YAML
  done
  echo "processors:"
  echo "  batch: {}"
  echo "exporters:"
  echo "  clickhouse:"
  echo "    endpoint: tcp://ch-server:9000?dial_timeout=10s"
  echo "    database: default"
  echo "    username: default"
  echo '    password: ""'
  echo "    create_schema: true"
  echo "    ttl: 720h"
  echo "service:"
  echo "  pipelines:"
  echo "    metrics:"
  printf "      receivers: ["
  printf '%s' "$(IFS=,; echo "${ADDRS[*]/#/snmp/}" | sed 's/\./_/g')"
  echo "]"
  echo "      processors: [batch]"
  echo "      exporters: [clickhouse]"
} > "$OUT"

echo "Wrote $OUT with ${#ADDRS[@]} device(s): ${ADDRS[*]}"
chmod +x "$0"
