#!/usr/bin/env bash
# Generate telegraf.d/agents.conf (the full [[inputs.snmp]] block) from
# default.exporters UNION an optional manual extra-targets file.
# Community is resolved at runtime via ${SNMP_COMMUNITY} (env); this file holds
# only device IPs and is gitignored.
set -euo pipefail

CH_CONTAINER="${CH_CONTAINER:-akvorado-clickhouse-1}"
EXTRA_FILE="${EXTRA_FILE:-$(dirname "$0")/snmp-extra-targets.txt}"
OUT="$(dirname "$0")/telegraf.d/agents.conf"
mkdir -p "$(dirname "$OUT")"

# Source 1: exporters discovered from the flow database.
mapfile -t ADDRS < <(docker exec -i "$CH_CONTAINER" clickhouse-client -q \
  "SELECT DISTINCT replaceRegexpOne(toString(ExporterAddress),'^::ffff:','') FROM default.exporters ORDER BY 1" 2>/dev/null || true)

# Source 2: optional manual extra targets (gitignored), one IP per line.
if [ -f "$EXTRA_FILE" ]; then
  while IFS= read -r line; do
    line="${line%%#*}"; line="$(echo "$line" | tr -d '[:space:]')"
    [ -n "$line" ] && ADDRS+=("$line")
  done < "$EXTRA_FILE"
fi

# Union: drop blanks, dedup.
mapfile -t ADDRS < <(printf '%s\n' "${ADDRS[@]}" | sed '/^$/d' | sort -u)
if [ "${#ADDRS[@]}" -eq 0 ]; then
  echo "No SNMP targets: default.exporters empty and no $EXTRA_FILE." >&2
  exit 1
fi

AGENTS=$(printf '"udp://%s:161", ' "${ADDRS[@]}" | sed 's/, $//')
cat > "$OUT" <<EOF
# GENERATED by gen-telegraf-agents.sh — do not edit; do not commit.
[[inputs.snmp]]
  agents = [${AGENTS}]
  version = 2
  community = "\${SNMP_COMMUNITY}"
  agent_host_tag = "source"
  timeout = "15s"
  retries = 2
  [[inputs.snmp.table]]
    name = "snmp"
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.31.1.1.1.1"
      name = "ifName"
      is_tag = true
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.31.1.1.1.18"
      name = "ifAlias"
      is_tag = true
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.2.2.1.1"
      name = "ifIndex"
      is_tag = true
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.31.1.1.1.6"
      name = "ifHCInOctets"
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.31.1.1.1.10"
      name = "ifHCOutOctets"
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.2.2.1.14"
      name = "ifInErrors"
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.2.2.1.20"
      name = "ifOutErrors"
    [[inputs.snmp.table.field]]
      oid = "1.3.6.1.2.1.2.2.1.8"
      name = "ifOperStatus"
EOF
echo "Wrote $OUT with ${#ADDRS[@]} agent(s): ${ADDRS[*]}"
